version: '3.8'

services:
  backend:
    image: ciphermun/my-backend:latest
    restart: unless-stopped
    ports:
      - '8000:8000'
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    image: ciphermun/my-frontend:latest
    restart: unless-stopped
    ports:
      - '80:80'
    depends_on:
      - backend
